channels:
  - conda-forge
  - r
  - genepattern
  - gurobi
dependencies:
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - rpy2
  - rise
  - jupyter_contrib_nbextensions
  - jupyter-wysiwyg
  - r-irkernel
  - r-tidyverse
  - gurobi
  - pip
  - pip:
      - julia
      
  
